##################################################################################################
# FILES - BACKEND
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: arcadia-np-backend
    service: arcadeia-np-backend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    name: arcadia-np-backend-80
  selector:
    app: arcadia-np-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: arcadia-np-backend
  labels:
    app: arcadia-np-backend
    version: v1
  annotations:
    ves.io/workload-flavor: medium
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arcadia-np-backend
      version: v1
  template:
    metadata:
      labels:
        app: arcadia-np-backend
        version: v1
    spec:
      containers:
      - env:
        - name: service_name
          value: backend
        image: pupapaik/backend:latest
        imagePullPolicy: IfNotPresent
        name: arcadia-np-backend
        ports:
        - containerPort: 8080
          protocol: TCP
---
##################################################################################################
# MAIN
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: arcadia-np-main
  labels:
    app: arcadia-np-main
    service: arcadia-np-main
spec:
  type: ClusterIP
  ports:
  - name: arcadia-np-main-80
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: arcadia-np-main
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: arcadia-np-main
  labels:
    app: arcadia-np-main
    version: v1
  annotations:
    ves.io/workload-flavor: medium
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arcadia-np-main
      version: v1
  template:
    metadata:
      labels:
        app: arcadia-np-main
        version: v1
    spec:
      containers:
      - env:
        - name: service_name
          value: arcadia-np-main
        image: pupapaik/main-app:latest
        imagePullPolicy: IfNotPresent
        name: arcadia-np-main
        ports:
        - containerPort: 8080
          protocol: TCP
---
##################################################################################################
# APP2
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: arcadia-np-app2
  labels:
    app: arcadia-np-app2
    service: arcadia-np-app2
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: arcadia-np-app2-80
    targetPort: 8080
  selector:
    app: arcadia-np-app2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: arcadia-np-app2
  labels:
    app: arcadia-np-app2
    version: v1
  annotations:
    ves.io/workload-flavor: medium
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arcadia-np-app2
      version: v1
  template:
    metadata:
      labels:
        app: arcadia-np-app2
        version: v1
    spec:
      containers:
      - env:
        - name: service_name
          value: arcadia-np-app2
        image: pupapaik/app2:latest
        imagePullPolicy: IfNotPresent
        name: arcadia-np-app2
        ports:
        - containerPort: 8080
          protocol: TCP
---
##################################################################################################
# APP3
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: arcadia-np-app3
  labels:
    app: arcadia-app3
    service: arcadia-np-app3
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: arcadia-np-app3-80
    targetPort: 8080
  selector:
    app: arcadia-np-app3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: arcadia-np-app3
  labels:
    app: arcadia-np-app3
    version: v1
  annotations:
    ves.io/workload-flavor: medium
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arcadia-np-app3
      version: v1
  template:
    metadata:
      labels:
        app: arcadia-np-app3
        version: v1
    spec:
      containers:
      - env:
        - name: service_name
          value: arcadia-app3
        image: pupapaik/app3:latest
        imagePullPolicy: IfNotPresent
        name: arcadia-np-app3
        ports:
        - containerPort: 8080
          protocol: TCP
---
